name: WIP Test the Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-the-thing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0

    - name: Setup Terraform 🧱
      uses: opentofu/setup-opentofu@v1

    - name: Outputs 🧱
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_KEY_ADO_NONPROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_SECRET_ADO_NONPROD }}
      run: |
        cd iac/
        tofu init
        tofu output -json parameters
        which tofu

    - name: Prepare deps
      run: npm ci

    - uses: ./
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_KEY_ADO_NONPROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_SECRET_ADO_NONPROD }}
      with:
        to: ssm
        tf-module-path: iac/
        secret-values: |
          {
            "jasonTest": "${{ secrets.jasonTest }}",
            "nickTest": "${{ secrets.nickTest }}"
          }
